# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FSCalendar_tutorial' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FSCalendar_tutorial
pod 'FSCalendar'
end
